# Generated by Django 2.1.5 on 2019-04-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontypefunctiontestcase',
            name='expected_return',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(blank=True),
        ),
    ]
