# Generated by Django 2.1.5 on 2019-04-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitfit', '0002_auto_20190415_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeParsons',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bitfit.Question')),
                ('lines', models.TextField()),
            ],
            options={
                'verbose_name': 'Parsons Problem Question',
            },
            bases=('bitfit.question',),
        ),
        migrations.CreateModel(
            name='QuestionTypeParsonsTestCase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bitfit.TestCase')),
                ('test_code', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='bitfit.QuestionTypeParsons')),
            ],
            options={
                'verbose_name': 'Parsons Problem Question Test Case',
            },
            bases=('bitfit.testcase',),
        ),
    ]
