# Generated by Django 2.1.5 on 2019-04-11 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitfit', '0002_auto_20190412_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontypefunctiontestcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='bitfit.QuestionTypeFunction'),
        ),
        migrations.AlterField(
            model_name='questiontypeprogramtestcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='bitfit.QuestionTypeProgram'),
        ),
    ]
